### PR TITLE
feat(theme): add pinky boom theme

### PR DESCRIPTION
**Pull request by mugiwarafx**

### CODE REVIEW

**Comment by admiraldus** [comment]
please add screenshots from the theme.

**Comment by mugiwarafx** [comment]
dark-pinky
dark-pinky-2
light-pinky
light-pinky-2

**Comment by dragonwocky** [comment]
from an aesthetic perspective, this feels incomplete to look at:

the dark mode theme seems like a mismatched mix of purple and pink thrown onto the text without altering anything else to match, and the light mode seems pretty much the same as normal except for bright pink primary colours & scrollbars and a pink sidebar with a massive white box on it.

if you like this look you can use it with the custom inserts extension, but the changes it makes aren't major or cohesive enough to qualify as a theme, sorry. closing this for now, but you're welcome to create a new pull request for it after addressing those things!

**Comment by mugiwarafx** [comment]
I agree with you! I did not touch many default vars, let me work in it! Now it's too shy to be a real boom, haha. I'll pull again when de work is done 😁

**Pull request closed without merging**
