### PR TITLE
Fix White Window Bug #298

### PR DESCRIPTION
**Pull request by Kirakeru**
Fix White Window Bug #298, as is described in https://github.com/notion-enhancer/notion-enhancer/issues/298#issuecomment-737280313.

### CODE REVIEW

**Comment by lhecht** [comment]
Thank you very much for this. For everyone who is impatient: To implement this on a windows machine go to the folder, that is shown, when you install notion-enhancer with npm. For me this was:  C:\Users\Username\AppData\Roaming\npm\node_modules\notion-enhancer. There you find the two files that are described in Kirakerus Fix. By just adding the lines and reopening Notion it worked again.

**Comment by admiraldus** [comment]
this fixes almost everything. but still when i open the enhancements menu, it opens "this pc" folder and when we enable tabs, notion gets stuck on the infinite loading screen.

**Comment by dragonwocky** [comment]
Not sure this is the best solution. While this (mostly) fixes things, the remote module was disabled for good reasons and it would probably be a good idea to work with that rather than just re-enabling it.

**Comment by dragonwocky** [comment]
...alright after looking into Notion's source it looks like they just did the bare minimum to get things working with the newer Electron but didn't actually stop using the remote module as recommended.

**Comment by Kirakeru** [comment]
> Not sure this is the best solution. While this (mostly) fixes things, the remote module was disabled for good reasons and it would probably be a good idea to work with that rather than just re-enabling it.

Maybe the Notion team would like to keep everything working first, and then try to provide better technical solutions in the future. Undoubtly, my commit is to be reverted someday, after both the Notion team and the enhancer community eventually get rid of the remote module. I'm also trying to find a way to fix this without enabling the deprecated remote module in a few days. Maybe polyfilling a small number of apis of the remote module could make things work.

P.S. This is actually my first pull request and I'm very glad to find it helpful to the community XD

**Comment by dragonwocky** [comment]
> I'm also trying to find a way to fix this without enabling the deprecated remote module in a few days

Unfortunately don't think this is possible. It might be a good idea to avoid using it in the enhancer, but since Notion itself still uses it the white screen bug will happen whenever it's not enabled enhancer or not. It might be possible to override where it's used (particularly where the `__electronApi` is defined - as far as I can tell that's where it's interacted with by the external/unreadable Notion code), but most of it is used synchronously, which wouldn't really work with waiting for a response to the ipc communication that would need to replace it.

**Pull request merged**
