### PR TITLE
add font variables for headings, headings input for font chooser and fix quote variable

### PR DESCRIPTION
**Pull request by admiraldus**
- new font variables for headings:
  - **`--theme_dark--font_headings`**
  - **`--theme_light--font_headings`**
- fix quote variable for theming:
  - **`--theme--font_quote: var(--theme_dark--font_sans);`** -> **`--theme--font_quote: var(--theme_dark--font_quote);`**
  - **`--theme--font_quote: var(--theme_light--font_sans);`** -> **`--theme--font_quote: var(--theme_light--font_quote);`**
- changes on @TorchAtlas's font chooser:
  - added a new input to change the font of headings.
  - version number: **`0.2.1`** -> ~~**`0.3.1`**~~ **`0.3.0`**.
- solution for issue https://github.com/notion-enhancer/notion-enhancer/issues/318

#### images
IMG
IMG

### CODE REVIEW

**Comment by torchatlas** [comment]
Since you have added separate font variables for each type of heading, wouldn't it make sense to have an input for each type of heading?

Also: Wouldn't 0.3.0 make more sense than 0.3.1?

Anyways, thanks for the recent commits on Font Chooser — the new functionality is good.

**Comment by admiraldus** [comment]
> Since you have added separate font variables for each type of heading, wouldn't it make sense to have an input for each type of heading?

a single input was requested for all of them on the issue and as you can see, inputs are increasing, wouldn't it be too crowded if i add inputs for each one separately?
> Also: Wouldn't 0.3.0 make more sense than 0.3.1?

yes, that makes more sense, i'm changing.

**Comment by dragonwocky** [comment]
should there be a separate variable for each size? for consistency of interpretation headings should probably be the same font, just different sizes. plus, the issue this was requested in said that they only needed/wanted one thing to change it for all sizes.

**Comment by admiraldus** [comment]
> should there be a separate variable for each size? for consistency of interpretation headings should probably be the same font, just different sizes. plus, the issue this was requested in said that they only needed/wanted one thing to change it for all sizes.

i think should there be because there may be themes that want to make them different and it will definitely work in the long run.

**Comment by dragonwocky** [comment]
> i think should there be because there may be themes that want to make them different and it will definitely work in the long run.


every variable decreases performance, though, so we shouldn't just add variables for the same of adding them if they're not actually needed.

if themes use a difference font for everything they can then the app would probably look too random/busy. consistency is a good thing for things that are expected to be the same. e.g. quotes being a different font to headers makes sense but headers being a different font to headers doesn't really.

**Comment by admiraldus** [comment]
> > i think should there be because there may be themes that want to make them different and it will definitely work in the long run.
> 
> every variable decreases performance, though, so we shouldn't just add variables for the same of adding them if they're not actually needed.
> 
> if themes use a difference font for everything they can then the app would probably look too random/busy. consistency is a good thing for things that are expected to be the same. e.g. quotes being a different font to headers makes sense but headers being a different font to headers doesn't really.

alright, i'll update mod.js in a few hours.

**Comment by admiraldus** [comment]
done! please take a look.

**Pull request merged**
