### PR TITLE
Extension: Notion Icons

### PR DESCRIPTION
**Pull request by CloudHill**
# Integration of [notion-icons](https://github.com/jayhxmo/notion-icons) into notion-enhancer as an extension.
This extension lets you use custom icon sets directly inside Notion by adding a tab into the icon-selection ui.

Icons

The extension works by overlaying the third tab (Upload by Link) and later submitting the selected icon's url as the icon link.

Icon sets are defined inside `icons.json`. At this point, the icon sets are still being pulled from the original [notion-icons](https://github.com/jayhxmo/notion-icons) repository, so adding more default icon sets are not yet possible (it technically is possible, but I think it'd be better to not have icons from many different sources by default).

## Custom JSON
Users can provide their own JSON file to include some of their own custom icon sets.
image

The JSON file should have one `icons` object which defines an array of icon set objects with the following properties:

| property               | description                                                                                                                                                            | type              |
| ---------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------- |
| `name`                 | name of the icon set.                                                                                                                                                  | string            |
| `source`               | if `sourceUrl` is defined: defines a list of the icons' filenames. otherwise, defines a list of urls, each pointing to an icon.                                        | array of strings  |
| `extension` (optional) | file extension (not necessary if `source` is an array of urls), e.g. `png`, `svg`.                                                                                     | string            |
| `sourceUrl` (optional) | defines a base url for all icons in the set.                                                                                                                           | string            |
| `count` (optional)     | if `sourceUrl` is also defined, the `source` filename will be iterated from `0` to `count` with an underscore `_` in between, i.e. `source_0`, `source_1`, `source_2`. | number            |
| `author` (optional)    | name of the icon set's author.                                                                                                                                         | string            |
| `authorUrl` (optional) | link to author's site.                                                                                                                                                 | string            |

### Example

The following JSON defines 3 icon sets taken from [Icons8](https://icons8.com/) and [Flaticon](https://www.flaticon.com/).

```JSON
{
  "icons": [
    {
      "name": "Icons8 Fluent",
      "sourceUrl": "https://img.icons8.com/fluent/280/000000/",
      "source": [
        "source-code",
        "forward",
        "fire-element"
      ],
      "extension": "png"
    },
    {
      "name": "Icons8 Mix",
      "source": [
        "https://img.icons8.com/ios/280/000000/source-code.png",
        "https://img.icons8.com/material/280/000000/forward.png",
        "https://img.icons8.com/color/280/000000/fire-element.png"
      ]
    },
    {
      "name": "Freepik Business",
      "sourceUrl": "https://www.flaticon.com/svg/static/icons/svg/3650/",
      "source": [
        "3650403", "3650408", "3650413", "3650417", "3650424",
        "3650429", "3650433", "3650437", "3650440", "3650444",
        "3650449", "3650451", "3650457", "3650462", "3650467"
      ],
      "extension": "svg",
      "author": "Freepik",
      "authorUrl": "http://www.freepik.com/"
    }
  ]
}
```

### CODE REVIEW

**Comment by CloudHill** [comment]
Since the icons need to be hosted somewhere and users shouldn't have to download them, I didn't include them in the extension folder. Any ideas on how to host it? A folder somewhere, or a separate repository maybe.

**Comment by admiraldus** [comment]
> Since the icons need to be hosted somewhere and users shouldn't have to download them, I didn't include them in the extension folder. Any ideas on how to host it? A folder somewhere, or a separate repository maybe.

custom inserts?

**Comment by CloudHill** [comment]
I'm talking about the png files currently living in https://github.com/jayhxmo/notion-icons, which defines the default icon set. I'd like to move them elsewhere where users can contribute their own icon sets for others to use.

**Comment by dragonwocky** [comment]
@CloudHill i've added you to https://github.com/notion-enhancer/icons

**Pull request merged**
