### PR TITLE
run in last notion app

### PR DESCRIPTION
**Pull request by superastorh**
I am fix some bug and it run

### CODE REVIEW

**Review by aminya — APPROVED** [review]
Fixes #453

**Comment by ryan-efendy** [comment]
@superastorh @aminya do we need to add `cac` as a dependency in `package.json`?

```
❯ npm i -g git+https://github.com/superastorh/notion-enhancer#a893c3f4a707e19c9f5f71cab77c67ae4e384b24
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /Users/ryanefendy/.nvm/versions/node/v16.6.1/bin/node /Users/ryanefendy/.nvm/versions/node/v16.6.1/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/ryanefendy/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/ryanefendy/.npm/_cacache/tmp/git-clone4oXz7s
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c node bin.js apply -y
npm ERR! npm ERR! node:internal/modules/cjs/loader:936
npm ERR! npm ERR!   throw err;
npm ERR! npm ERR!   ^
npm ERR! npm ERR!
npm ERR! npm ERR! Error: Cannot find module 'cac'
npm ERR! npm ERR! Require stack:
npm ERR! npm ERR! - /Users/ryanefendy/.npm/_cacache/tmp/git-clone4oXz7s/bin.js
npm ERR! npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR! npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
npm ERR! npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR! npm ERR!     at require (node:internal/modules/cjs/helpers:94:18)
npm ERR! npm ERR!     at Object.<anonymous> (/Users/ryanefendy/.npm/_cacache/tmp/git-clone4oXz7s/bin.js:11:13)
npm ERR! npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
npm ERR! npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
npm ERR! npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR! npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR! npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12) {
npm ERR! npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR! npm ERR!   requireStack: [ '/Users/ryanefendy/.npm/_cacache/tmp/git-clone4oXz7s/bin.js' ]
npm ERR! npm ERR! }
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/ryanefendy/.npm/_logs/2021-09-14T23_46_28_313Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ryanefendy/.npm/_logs/2021-09-14T23_46_28_347Z-debug.log
```

**Comment by dragonwocky** [comment]
p.s. this is fixed in [notion-repackaged](https://github.com/notion-enhancer/notion-repackaged/releases/) - uninstall notion & the npm version of notion enhancer, then install the relevant file from here (e.g. a .exe for windows and a .dmg for macOS)

**Comment by dragonwocky** [comment]
@ryan-efendy I wouldn't clone from this - even if you can't use notion-repackaged, the fixes here aren't enough to get the npm version at a working level. You would need to install the npm release of the enhancer and then manually apply these patches (some to the enhancer, some to notion): https://github.com/notion-enhancer/notion-repackaged/tree/main/patches

**Pull request closed without merging**
